<div class="pricetable">
  <div class="pricetable-inner">
    <?php foreach((array) $table as $i => $column) : ?>
    <div class="<?php print implode(' ', $column['classes']) ?>" style="width:<?php print $column['width'] ?>%">
      <div class="column-inner">
        <div class="header">
          <h3 class="name"><?php print $column['title']?></h3>
          <h3 class="price"><?php print $column['price']?></h3>
          <?php print $column['detail']?></div>
        <div class="features">
          <?php if(!empty($column['features'])) : ?>
          <?php foreach($column['features'] as $j => $feature) : ?>
          <div class="feature <?php print $j == 0 ? 'first' : '' ?>"> <?php print $feature['title'] ?>
            <?php if(!empty($feature['sub'])) : ?>
            <small><?php print $feature['sub'] ?></small>
            <?php endif; ?>
          </div>
          <?php endforeach ?>
          <?php endif; ?>
        </div>
        <div class="button-container"><a href="<?php print empty($column['url']) ? '#' : $column['url'] ?>"><span><?php print empty($column['button']) ? __('Select', 'pricetable') : $column['button'] ?></span></a></div>
      </div>
    </div>
    <?php endforeach ?>
    <div class="pricetable-clear"></div>
  </div>
</div>